name: dart_nats_client
description: A Dart client for the NATS messaging system. Design to use with Dart and flutter. Forked from https://github.com/chartchuo/dart-nats
version: 0.1.12
homepage: https://github.com/iakrevetkho
repository: https://github.com/iakrevetkho/dart-nats

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # Logger
  logger: ^0.9.4
  # Universal socket io
  universal_io: ^1.0.1

dev_dependencies:
  # Unit tests
  test: ^1.9.4
  # Static analyze
  effective_dart: ^1.3.0
  pedantic: ^1.9.0
  # UUID generator
  uuid: ^2.2.2
