name: Publish Dart Package

on:
  push:
    branches:
      # Push events on master
      - master
      # Push events on develop
      - develop
    tags:
      # Push events for every version tag
      - v*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.DART_PUB_CREDS }}
          flutter_package: false
          skip_test: true
          dry_run: true
